spring:
  profiles:
    active: dev
  datasource:
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    url: "${DB_URL}"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: 'true'
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: people-server
  flyway:
    baseline-on-migrate: true
server:
  port: '8080'
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost

logging:
  level:
    org:
      springframework:
        security: DEBUG