name: Build and Push to GAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: "latest"

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Authenticate to Artifact Registry
        run: |
          docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://europe-west2-docker.pkg.dev

      - name: Build and push Docker image to GAR
        run: |
          docker build -t europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsolutions-repository/server:latest .
          docker push europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsolutions-repository/server:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy server \
            --image=europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsolutions-repository/server:latest \
            --platform=managed \
            --region=europe-west2 \
            --allow-unauthenticated
