name: Build, Test, and Check Coverage

on:
  push:
    branches:
      - work

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run tests and generate coverage report
        run: |
          mvn clean test jacoco:report

      - name: Extract coverage percentage
        id: extract-coverage
        run: |
          csv_file="target/site/jacoco/jacoco.csv"
          if [ ! -f "$csv_file" ]; then
          echo "Error: CSV file not found."
          exit 1
          fi
          covered=$(awk -F ',' '{sum += $5} END {print sum}' "$csv_file")
          missed=$(awk -F ',' '{sum += $4} END {print sum}' "$csv_file")
          if [[ -n $covered && -n $missed ]]; then
          coverage=$(echo "scale=2; ($covered / ($covered + $missed)) * 100" | bc)
          echo "::set-output name=coverage::$coverage"
          else
          echo "Error: Unable to extract coverage values."
          exit 1
          fi

      - name: Create coverage badge
        id: create-badge
        run: |
          cov="${{ steps.extract-coverage.outputs.coverage }}"
          jq -n --arg cov "$cov" '{schemaVersion: 1, label: "Coverage", message: ($cov + "%"), color: "brightgreen"}' > coverage-badge.json

      - name: Upload coverage badge as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage-badge.json

      - name: Upload coverage badge as raw artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge-raw
          path: coverage-badge.json

      - name: Get coverage badge JSON URL
        id: get-badge-url
        run: |
          echo "::set-output name=url::https://github.com/${{ github.repository }}/actions/artifacts/${{ steps.upload-coverage-badge-raw.outputs.artifact_id }}/raw/coverage-badge.json"

      - name: Print coverage badge URL
        run: |
          echo "Coverage badge URL: ${{ steps.get-badge-url.outputs.url }}"

      - name: Debug Coverage Value
        run: |
          echo "Coverage value: ${{ steps.extract-coverage.outputs.coverage }}"

      - name: Replace coverage placeholder in README.md
        run: sed -i "s/%COVERAGE%/${{ steps.extract-coverage.outputs.coverage }}/g" README.md
        working-directory: ${{ github.workspace }}
