name: Build, Test, and Check Coverage

on:
  push:
    branches:
      - work

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run tests and generate coverage report
        run: |
          mvn clean test jacoco:report

      - name: Extract coverage percentage
        id: extract-coverage
        run: |
          coverage=$(grep -Po "(?<=<counter type=\"INSTRUCTION\" covered=\")(.*?)(?=\")" target/site/jacoco/jacoco.xml)
          echo "::set-output name=coverage::$coverage"

      - name: Create coverage badge
        id: create-badge
        run: |
          echo "[![Coverage](https://img.shields.io/badge/Coverage-${{ steps.extract-coverage.outputs.coverage }}%25-brightgreen)](https://github.com/your-repository)" > coverage-badge.md

      - name: Upload coverage badge as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage-badge.md

      - name: Update README.md with coverage badge
        run: |
          echo "![](./coverage-badge.md)" >> README.md